;SECOND STAGE BOOT LOADER - SSNAKEOS.SYS
 
ORG 0x0
BITS 16

JMP BeginSecondStage

PRINTCHAR16:				;PRINT A CHARACTER
 MOV AH,0x0E
 MOV BH,0x00
 MOV BL,0x07
 
 INT 0x10
 RET
 
PRINTSTR16:					;PRINT A STRING
 NEXT:
 MOV AL,[SI]				;MOVE CHARACTER INTO AL
 INC SI						;INCREMENT MEMORY LOCATION
 OR AL,AL					;CHECK FOR ZERO-TERMINATED STRING
 JZ EXIT
 CALL PRINTCHAR162			;PRINT THE CURRENT CHAR
 JMP NEXT					;LOOP BACK B/C IT HAS NOT REACHED ZERO
 EXIT:
 RET

BeginSecondStage:
 CLI
 PUSH CS
 POP DS
 STI
 
 MOV SI,SecondStageGrab
 CALL PRINTSTR16
 
 
 
 
 CLI						;CLEAR INTERUPTS
 HLT						;HALT SYSTEM
 JMP $

 SecondStageGrab	DB 'Second Stage - Fuck ya!',13,10,0
